### ISSUE TITLE
Buddy Status property not updating correctly

### ISSUE THREAD

**Issue by mus0u** [zaki/skypemac#1]
I'm trying to detect changes in the status of users on the buddy list, but even when they change from available to away or back again, the integers returned by the .buddy_status property of the user do not change. I've tried to debug this issue myself, but I don't know AppleScript, so I'm not 100% sure how to go about it. Do you have any ideas / workarounds that would allow me to detect changes in status of users on the buddy list?

**Comment by zaki** [comment]
Hi,

`BUDDYSTATUS` tells you whether the contact is on your contact list or not (according to the skype public api: 0 – never been in contact list., 1 – deleted from contact list. (read-write), 2 – pending authorisation. (read-write), 3 – added to contact list.) For more information, see: http://developer.skype.com/public-api-reference#OBJECT_USER

You probably want to use the `online_status` property, which returns strings like "OFFLINE" or "ONLINE" or "AWAY". I just tested and it seems to appropriately update when the contact changes status.

With AppleScript, it is not possible however to get notified of this change, you will have to query (poll). For example:

```
>> u = SkypeMac::User.new('echo123')
=> echo123
>> u.online_status
=> "OFFLINE"
>> u.online_status
=> "ONLINE"
>> u.online_status
=> "AWAY"
```

Hope this helps,
Zaki

**Comment by mus0u** [comment]
Great! That's exactly what I needed. Thanks!
